Repository HispaniaSS13/ParadiseHispania, pull requests merged in 2022-12, with the labels that each got.

#11 SAD TROMBONE RETURNS
  code/modules/pda/cart.dm
  modular_hispania/code/modules/pda/utilities.dm
  paradise.dme
Labels: Tweak, Sound

#24 Embed MENTION
  code/game/gamemodes/game_mode.dm
Labels: Tweak, Reconstruyendo la Sociedad de NUEVO

#22 RuneChat Above Layer
  code/datums/chatmessage.dm
Labels: Tweak, Reconstruyendo la Sociedad de NUEVO

#15 Ported cloaker and sus prototype
  modular_hispania/code/datums/supplypacks.dm
  modular_hispania/code/game/objects/items/devices/syndieprototype.dm
  modular_hispania/code/modules/clothing/mask/gasmask.dm
  modular_hispania/icons/obj/syndieproto.dmi
  modular_hispania/sound/voice/hailer/cloaker/beated.ogg
  modular_hispania/sound/voice/hailer/cloaker/beep.ogg
  modular_hispania/sound/voice/hailer/cloaker/celilitis.ogg
  modular_hispania/sound/voice/hailer/cloaker/corners.ogg
  modular_hispania/sound/voice/hailer/cloaker/cry.ogg
  modular_hispania/sound/voice/hailer/cloaker/difficulty-tweak.ogg
  modular_hispania/sound/voice/hailer/cloaker/expected.ogg
  modular_hispania/sound/voice/hailer/cloaker/forums.ogg
  modular_hispania/sound/voice/hailer/cloaker/hitting-yourself.ogg
  modular_hispania/sound/voice/hailer/cloaker/im-late.ogg
  modular_hispania/sound/voice/hailer/cloaker/meeting.ogg
  modular_hispania/sound/voice/hailer/cloaker/missed.ogg
  modular_hispania/sound/voice/hailer/cloaker/no-return.ogg
  modular_hispania/sound/voice/hailer/cloaker/not-tough.ogg
  modular_hispania/sound/voice/hailer/cloaker/pants.ogg
  modular_hispania/sound/voice/hailer/cloaker/resisting.ogg
  modular_hispania/sound/voice/hailer/cloaker/s-word.ogg
  modular_hispania/sound/voice/hailer/cloaker/speak-up.ogg
  modular_hispania/sound/voice/hailer/cloaker/wish-true.ogg
  modular_hispania/sound/voice/hailer/cloaker/work-smarter.ogg
  paradise.dme
Labels: Feature, Sound, Reconstruyendo la Sociedad de NUEVO

#18 Clothelate is BACK!
  modular_hispania/code/__DEFINES/wires.dm
  modular_hispania/code/datums/wires/clothelate.dm
  modular_hispania/code/game/machinery/clothelate.dm
  modular_hispania/code/game/machinery/constructable_frame.dm
  modular_hispania/code/modules/research/designs/clothelate_designs.dm
  modular_hispania/code/modules/research/designs/machine_designs.dm
  modular_hispania/code/modules/research/research.dm
  modular_hispania/icons/obj/clothelate.dmi
  paradise.dme
  tgui/packages/tgui/interfaces/Clothelate.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Reconstruyendo la Sociedad de NUEVO
