Repository HispaniaSS13/ParadiseHispania, pull requests merged in 2023-02, with the labels that each got.

#79 Limpieza modular hispania
  code/game/gamemodes/blob/blob.dm
  code/game/gamemodes/changeling/changeling.dm
  code/game/gamemodes/cult/cult.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/gamemodes/vampire/vampire_gamemode.dm
  code/game/machinery/doors/airlock.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/devices/scanners.dm
  modular_hispania/code/game/gamemodes/blob.dm
  modular_hispania/code/game/gamemodes/changeling.dm
  modular_hispania/code/game/gamemodes/cult.dm
  modular_hispania/code/game/gamemodes/traitor.dm
  modular_hispania/code/game/gamemodes/vampire_gamemode.dm
  modular_hispania/code/game/machinery/doors/airlock.dm
  modular_hispania/code/game/objects/effects/landmarks.dm
  modular_hispania/code/game/objects/items/devices/scanners.dm
  modular_hispania/icons/effects/spawner_icons.dmi
  paradise.dme
Labels: Refactor

#68 The Engiberia Update
  _maps/maphispania_files/hispania/hispania.dmm
  modular_hispania/code/game/area/hispania_areas.dm
  modular_hispania/icons/turf/areas.dmi
  paradise.dme
Labels: Mappeo, Reconstruyendo la Sociedad de NUEVO

#84 DaBaby Remix
  _maps/maphispania_files/dadaby/dadaby.dmm
  paradise.dme
Labels: Mappeo, merge-conflict

#87 Portea cosas chaplain
  _maps/maphispania_files/hispania/hispania.dmm
  code/modules/mob/living/carbon/human/update_icons.dm
  modular_hispania/code/game/machinery/vending.dm
  modular_hispania/code/game/objects/items.dm
  modular_hispania/code/game/objects/items/weapons/holy_weapons.dm
  modular_hispania/code/game/objects/structures/stool_bed_chair_nest/bed.dm
  modular_hispania/code/modules/clothing/head/misc.dm
  modular_hispania/code/modules/clothing/under/jobs/civilian.dm
  modular_hispania/code/modules/mob/living/simple_animal/friendly/owl.dm
  modular_hispania/code/modules/reagents/chemistry/reagents/water.dm
  modular_hispania/icons/obj/vending.dmi
  modular_hispania/sound/mob/owl_hoot.ogg
  paradise.dme
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#74 Nuevo evento, baños tapados!
  code/modules/events/event_container.dm
  modular_hispania/code/game/objects/items.dm
  modular_hispania/code/game/objects/items/plunger.dm
  modular_hispania/code/game/objects/structures/crates_lockers/closets/job_closets.dm
  modular_hispania/code/modules/events/event_container.dm
  modular_hispania/code/modules/events/toilets_clog.dm
  modular_hispania/code/modules/mob/living/silicon/robot/robot_modules.dm
  modular_hispania/code/modules/research/designs/autolathe_deisgns.dm
  modular_hispania/icons/mob/head.dmi
  modular_hispania/icons/obj/clothing/hats.dmi
  modular_hispania/sound/effects/plunger.ogg
  paradise.dme
Labels: Evento, merge-conflict

#62 Nuevo JOB aprendiz , limitado
  code/game/jobs/job/assistant.dm
  code/game/jobs/job_exp.dm
  code/modules/client/preference/character.dm
  modular_hispania/code/game/jobs/job/assistant.dm
  modular_hispania/code/game/jobs/job/job.dm
  paradise.dme
Labels: Tweak, Changes-Requested

#107 Agrega stun a los banana cream pies y sprites para cuando golpean a alguien con uno.
  code/modules/mob/living/carbon/human/human_update_icons.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/baked_goods.dm
  modular_hispania/icons/mob/creampie.dmi
Labels: Sprites, Feature

#123 Quita cyberiad.dmm de votacion de mapa
  code/modules/mapping/cyberiad.dm
Labels: Fix

#115 Lock2
  modular_hispania/code/game/machinery/autolathe_datums.dm
  modular_hispania/code/game/machinery/doors/airlock.dm
  modular_hispania/code/game/machinery/doors/airlock_electronics.dm
  modular_hispania/code/game/objects/structures/door_assembly.dm
  modular_hispania/icons/obj/doors/airlocks/station/doorkeypad.dmi
  modular_hispania/icons/obj/doors/door_assembly.dmi
  paradise.dme
Labels: Feature

#100 Repara bug possessed blade y agrega una habilidad
  modular_hispania/code/modules/mob/living/simple_animal/shade.dm
  modular_hispania/sound/effects/endure.ogg
  paradise.dme
Labels: Feature

#127 fix leyes de la ia y borgs
  modular_hispania/code/datums/ai_law_sets.dm
  paradise.dme
Labels: Fix

#126 fix drake loot
  modular_hispania/code/modules/mob/living/simple_animal/hostile/megafauna/drake.dm
Labels: Fix

#125 nanomaps fix try2
  .github/workflows/render_nanomaps.yml
Labels: Fix

#128 fix atmos enginebra
  _maps/maphispania_files/hispania/hispania.dmm
Labels: Fix

#130 nanomap manual
  code/modules/client/asset_cache.dm
  icons/_nanomaps/Dababy_nanomap_z1.png
  icons/_nanomaps/Hispania_nanomap_z1.png
Labels: Fix
