Repository HispaniaSS13/ParadiseHispania, pull requests merged in 2023-01, with the labels that each got.

#19 KA experimentales
  modular_hispania/code/modules/mining/machine_vending.dm
  modular_hispania/code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  modular_hispania/icons/obj/projectiles.dmi
  paradise.dme
Labels: Tweak, Feature, Reconstruyendo la Sociedad de NUEVO

#36 Webhooks para Notas y Bans
  code/__DEFINES/misc.dm
  code/controllers/configuration/sections/discord_configuration.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/db_ban/functions.dm
  code/modules/admin/sql_notes.dm
  code/modules/admin/topic.dm
  config/example/config.toml
Labels: Discord

#31 Vuelve el noose
  modular_hispania/code/game/objects/items/miscellaneous/noose.dm
  modular_hispania/code/modules/crafting/recipes.dm
  modular_hispania/icons/obj/miscellaneous.dmi
  modular_hispania/sound/effects/noose_idle.ogg
  modular_hispania/sound/effects/noosed.ogg
  paradise.dme
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#27 Sonidos medbay
  code/game/objects/items/devices/scanners.dm
  modular_hispania/code/game/objects/items/devices/handheld_defib.dm
  modular_hispania/code/game/objects/items/devices/scanners.dm
  modular_hispania/code/game/objects/items/devices/sensor_device.dm
  modular_hispania/code/game/objects/items/weapons/defib.dm
  modular_hispania/code/game/objects/items/weapons/storage/firstaid.dm
  modular_hispania/code/modules/food_and_drinks/drinks/bottle.dm
  modular_hispania/code/modules/reagents/reagent_containers/bottle.dm
  modular_hispania/code/modules/reagents/reagent_containers/dropper.dm
  modular_hispania/code/modules/reagents/reagent_containers/glass_containers.dm
  modular_hispania/code/modules/reagents/reagent_containers/syringes.dm
  modular_hispania/code/modules/surgery/tools.dm
  modular_hispania/sound/item/items_pickup_1.ogg
  modular_hispania/sound/item/items_pickup_2.ogg
  modular_hispania/sound/item/items_pickup_3.ogg
  modular_hispania/sound/medbay/beaker_drop.ogg
  modular_hispania/sound/medbay/beaker_pickup.ogg
  modular_hispania/sound/medbay/bottle_drop.ogg
  modular_hispania/sound/medbay/bottle_pickup.ogg
  modular_hispania/sound/medbay/cardboardbox_drop.ogg
  modular_hispania/sound/medbay/cardboardbox_pickup.ogg
  modular_hispania/sound/medbay/defib_pickup.ogg
  modular_hispania/sound/medbay/device_drop.ogg
  modular_hispania/sound/medbay/device_pickup.ogg
  modular_hispania/sound/medbay/healthscanner_used.ogg
  modular_hispania/sound/medbay/knife1_pickup.ogg
  modular_hispania/sound/medbay/knife2_drop.ogg
  modular_hispania/sound/medbay/metal_drop.ogg
  modular_hispania/sound/medbay/needle_drop.ogg
  modular_hispania/sound/medbay/needle_pickup.ogg
  modular_hispania/sound/medbay/pildora.ogg
  modular_hispania/sound/medbay/pillbottle.ogg
  modular_hispania/sound/medbay/pillbottle_drop.ogg
  modular_hispania/sound/medbay/surgery1_pickup.ogg
  modular_hispania/sound/medbay/surgery2_pickup.ogg
Labels: Sound

#41 Los borgs ahora pueden interactuar con los tank dispenser
  modular_hispania/code/game/objects/structures/tank_dispenser.dm
  paradise.dme
Labels: Tweak

#44 Agrega el Halt security
  modular_hispania/code/game/machinery/vending.dm
Labels: Tweak

#29 Agrega destruccion de maquinas override de la IA
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  modular_hispania/code/modules/mob/mimic.dm
  paradise.dme
Labels: Tweak

#43 Humo al romper Airlocks
  code/game/machinery/doors/airlock.dm
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#21 PoliceTape / Inge + Sec
  modular_hispania/code/game/objects/items/policetape.dm
  modular_hispania/code/game/objects/items/weapons/storage/belt.dm
  modular_hispania/game/machinery/vendors/departmental_vendors.dm
  modular_hispania/icons/effects/hazard_tape.dmi
  modular_hispania/icons/obj/policetape.dmi
  paradise.dme
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#26 Feed me, evento de comida ha vuelto con mejoras
  _maps/map_files/cyberiad/cyberiad.dmm
  code/__DEFINES/mobs.dm
  code/_globalvars/mapping.dm
  code/game/objects/effects/landmarks.dm
  code/modules/events/event_container.dm
  code/modules/events/event_procs.dm
  code/modules/food_and_drinks/food/snacks.dm
  modular_hispania/code/modules/events/feedme.dm
  modular_hispania/icons/mob/comensales.dmi
  paradise.dme
Labels: Tweak, Evento

#32 Spare limitaciones abductor
  modular_hispania/code/game/objects/items/weapons/cards_ids.dm
  paradise.dme
Labels: Balance, Tweak

#37 Vuelve cluwne floor
  code/modules/events/event_container.dm
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#47 [Sprites] Re-sprite de Medbay
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/medical.dm
  modular_hispania/code/game/objects/items/weapons/storage/belt.dm
  modular_hispania/code/game/objects/items/weapons/storage/garment.dm
  modular_hispania/code/game/objects/structures/crates_lockers/closets/job_closets.dm
  modular_hispania/code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  modular_hispania/code/modules/clothing/gloves/color.dm
  modular_hispania/code/modules/clothing/head/jobs.dm
  modular_hispania/code/modules/clothing/head/soft_caps.dm
  modular_hispania/code/modules/clothing/shoes/colour.dm
  modular_hispania/code/modules/clothing/suits/jobs.dm
  modular_hispania/code/modules/clothing/suits/labcoat.dm
  modular_hispania/code/modules/clothing/under/jobs/medical.dm
  modular_hispania/icons/mob/clothing/belt.dmi
  modular_hispania/icons/mob/clothing/gloves.dmi
  modular_hispania/icons/mob/clothing/head/beret.dmi
  modular_hispania/icons/mob/clothing/head/hats.dmi
  modular_hispania/icons/mob/clothing/shoes.dmi
  modular_hispania/icons/mob/clothing/species/grey/belt.dmi
  modular_hispania/icons/mob/clothing/species/grey/gloves.dmi
  modular_hispania/icons/mob/clothing/species/grey/head/beret.dmi
  modular_hispania/icons/mob/clothing/species/grey/head/hats.dmi
  modular_hispania/icons/mob/clothing/species/grey/shoes.dmi
  modular_hispania/icons/mob/clothing/species/grey/suits/armor.dmi
  modular_hispania/icons/mob/clothing/species/grey/suits/labcoats.dmi
  modular_hispania/icons/mob/clothing/species/grey/under/medical.dmi
  modular_hispania/icons/mob/clothing/species/vox/gloves.dmi
  modular_hispania/icons/mob/clothing/species/vox/head/beret.dmi
  modular_hispania/icons/mob/clothing/species/vox/head/hats.dmi
  modular_hispania/icons/mob/clothing/species/vox/shoes.dmi
  modular_hispania/icons/mob/clothing/species/vox/suits/armor.dmi
  modular_hispania/icons/mob/clothing/species/vox/suits/labcoats.dmi
  modular_hispania/icons/mob/clothing/species/vox/under/medical.dmi
  modular_hispania/icons/mob/clothing/suits/armor.dmi
  modular_hispania/icons/mob/clothing/suits/labcoats.dmi
  modular_hispania/icons/mob/clothing/under/medical.dmi
  modular_hispania/icons/obj/clothing/belts.dmi
  modular_hispania/icons/obj/clothing/gloves.dmi
  modular_hispania/icons/obj/clothing/head/berets.dmi
  modular_hispania/icons/obj/clothing/head/hats.dmi
  modular_hispania/icons/obj/clothing/head/helmet.dmi
  modular_hispania/icons/obj/clothing/shoes.dmi
  modular_hispania/icons/obj/clothing/suits/armor.dmi
  modular_hispania/icons/obj/clothing/suits/labcoats.dmi
  modular_hispania/icons/obj/clothing/under/medical.dmi
  paradise.dme
Labels: Sprites, Héroe de Hispania

#33 xtra is_back
  _maps/map_files/cyberiad/cyberiad.dmm
  modular_hispania/code/game/machinery/vending.dm
  modular_hispania/icons/obj/vending.dmi
Labels: Feature, Reconstruyendo la Sociedad de NUEVO, Ume

#51 [Fixes] Los cascos de los hardsuit ya no son invisibles
  modular_hispania/code/modules/clothing/head/helmets.dm
  paradise.dme
Labels: Fix

#49 NO MAS MENCIONES SI NO HAY ADMINS AL INICIAR UNA RONDA.
  code/controllers/subsystem/ticker.dm
Labels: Fix, Discord

#50 Fix sonidos med
  paradise.dme
Labels: Fix

#46 HispaniaboxV5 Radial
  code/__DEFINES/sound.dm
  code/__HELPERS/unsorted.dm
  code/modules/client/preference/preferences_toggles.dm
  code/modules/client/preference/preferences_volume_mixer.dm
  modular_hispania/hispania/game/machinery/jukebox.dm
Labels: Tweak

#39 Los borgs de ingenieria ahora pueden tomar sheets de minerales
  modular_hispania/code/modules/mob/living/silicon/robot/drone/drone_items.dm
  paradise.dme
Labels: Tweak, Assriel, merge-conflict

#45 Nueva vending productos PREMIUM
  _maps/map_files/cyberiad/cyberiad.dmm
  code/modules/customitems/item_defines.dm
  modular_hispania/code/__DEFINES/economy.dm
  modular_hispania/code/game/objects/miscellaneous/paintkits_items.dm
  modular_hispania/hispania/game/machinery/premium_vending.dm
  modular_hispania/icons/obj/miscellaneous.dmi
  modular_hispania/icons/obj/vending.dmi
  modular_hispania/sound/effects/mongos.ogg
  paradise.dme
Labels: Feature

#35 mas sonidos sec
  modular_hispania/code/game/objects/items/weapons/handcuffs.dm
  modular_hispania/code/game/objects/items/weapons/storage/boxes.dm
  modular_hispania/code/modules/clothing/clothing.dm
  modular_hispania/code/modules/clothing/gloves/rings.dm
  modular_hispania/code/modules/clothing/head/helmets.dm
  modular_hispania/code/modules/vehicle/vehicle.dm
  modular_hispania/sound/items/accesory_drop.ogg
  modular_hispania/sound/items/accesory_pickup.ogg
  modular_hispania/sound/items/ammobox.ogg
  modular_hispania/sound/items/glasses.ogg
  modular_hispania/sound/items/handcuffs_drop.ogg
  modular_hispania/sound/items/handcuffs_pickup.ogg
  modular_hispania/sound/items/hat_drop.ogg
  modular_hispania/sound/items/hat_pickup.ogg
  modular_hispania/sound/items/helmet_drop.ogg
  modular_hispania/sound/items/helmet_pickup.ogg
  modular_hispania/sound/items/ring_drop.ogg
  modular_hispania/sound/items/ring_pickup.ogg
  paradise.dme
Labels: Sound, Ume, Assriel, merge-conflict

#52 Fix Security Vending
  modular_hispania/code/game/machinery/vending.dm
  modular_hispania/game/machinery/vendors/departmental_vendors.dm
  paradise.dme
Labels: Fix

#30 Cargo train
  _maps/map_files/cyberiad/cyberiad.dmm
  code/modules/vehicle/vehicle.dm
  modular_hispania/code/modules/supply/supply_packs/pack_miscellaneous.dm
  modular_hispania/code/modules/vehicles/cargo_train.dm
  modular_hispania/code/modules/vehicles/train.dm
  modular_hispania/code/modules/vehicles/vehicleh.dm
  modular_hispania/icons/obj/vehicles.dmi
  modular_hispania/sound/effects/engine_start.ogg
  modular_hispania/sound/effects/engine_stop.ogg
  modular_hispania/sound/effects/key_insert.ogg
  paradise.dme
Labels: Ume, Assriel, merge-conflict, Changes-Requested

#38 Vuelven TODAS las comidas
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  modular_hispania/code/game/objects/items/trash.dm
  modular_hispania/code/modules/food_and_drinks/condiments.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/baked_goods.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/candy.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/canned_food.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/ingredients.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/meat.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/misc.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/other_snacks.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/sandwiches.dm
  modular_hispania/code/modules/food_and_drinks/food/foods/soups.dm
  modular_hispania/code/modules/food_and_drinks/recipes/recipes_candy.dm
  modular_hispania/code/modules/food_and_drinks/recipes/recipes_grill.dm
  modular_hispania/code/modules/food_and_drinks/recipes/recipes_microwave.dm
  modular_hispania/code/modules/food_and_drinks/recipes/recipes_mixer.dm
  modular_hispania/code/modules/food_and_drinks/recipes/recipes_oven.dm
  modular_hispania/code/modules/food_and_drinks/recipes/tablecraft.dm
  modular_hispania/code/modules/hydroponics/anonna.dm
  modular_hispania/code/modules/hydroponics/avocado.dm
  modular_hispania/code/modules/hydroponics/cactus.dm
  modular_hispania/code/modules/hydroponics/coconut.dm
  modular_hispania/code/modules/hydroponics/kiwi.dm
  modular_hispania/code/modules/hydroponics/mango.dm
  modular_hispania/code/modules/hydroponics/mate.dm
  modular_hispania/code/modules/hydroponics/money.dm
  modular_hispania/code/modules/hydroponics/mushrooms.dm
  modular_hispania/code/modules/hydroponics/nispero.dm
  modular_hispania/code/modules/hydroponics/peach.dm
  modular_hispania/code/modules/hydroponics/pepper.dm
  modular_hispania/code/modules/hydroponics/ricinus.dm
  modular_hispania/code/modules/hydroponics/strawberry.dm
  modular_hispania/code/modules/mob/living/simple_animal/kiwi.dm
  modular_hispania/icons/mob/animals.dmi
  modular_hispania/icons/obj/candy.dmi
  modular_hispania/icons/obj/canned_food.dmi
  modular_hispania/icons/obj/containers.dmi
  modular_hispania/icons/obj/food.dmi
  modular_hispania/icons/obj/slimecookies.dmi
  modular_hispania/icons/obj/trash.dmi
  modular_hispania/sound/misc/donkselfheat.ogg
  modular_hispania/sound/misc/monke_eat.ogg
  paradise.dme
Labels: Héroe de Hispania, Reconstruyendo la Sociedad de NUEVO, Ume, Assriel, merge-conflict

#42 Balanceo terrors y xenos
  code/modules/mob/living/simple_animal/hostile/terror_spiders/terror_spiders.dm
  modular_hispania/code/__HELPERS/funciones_hispa.dm
  modular_hispania/code/modules/mob/living/carbon/alien/alien.dm
  modular_hispania/code/modules/mob/living/simple_animal/hostile/terror_spiders.dm
  paradise.dme
Labels: Tweak, Evento, merge-conflict

#55 [Fixes] 10 razones por las que no hacer un resprite
  modular_hispania/icons/mob/clothing/head/helmet.dmi
  modular_hispania/icons/mob/clothing/species/grey/head/helmet.dmi
  modular_hispania/icons/mob/clothing/species/vox/head/helmet.dmi
  modular_hispania/icons/obj/clothing/head/helmet.dmi
Labels: Fix

#56 Fix noose
  modular_hispania/code/game/objects/items/miscellaneous/noose.dm
Labels: Fix

#57 HispaniaboxV6 Rango Musica
  modular_hispania/hispania/game/machinery/jukebox.dm
  paradise.dme
Labels: Tweak, Sound

#63 Readys visibles
  code/modules/mob/new_player/new_player.dm
Labels: Héroe de Hispania

#59 Trae las Seeds hispania y otros drinks
  code/_globalvars/lists/reagents.dm
  modular_hispania/code/game/machinery/vending.dm
  modular_hispania/code/modules/hydroponics/agave.dm
  modular_hispania/code/modules/hydroponics/grown/mushrooms.dm
  modular_hispania/code/modules/reagents/chemistry/reagents/drinks.dm
  modular_hispania/code/modules/reagents/chemistry/recipes/drinks.dm
  modular_hispania/icons/obj/drinks.dmi
  paradise.dme
Labels: Ume

#64 Vuelve poder genetico quitado
  code/game/gamemodes/setupgame.dm
  modular_hispania/code/game/dna/genes/goon_powers.dm
  modular_hispania/sound/effects/superfart.ogg
  paradise.dme
Labels: Feature, Héroe de Hispania

#73 [Fix] Menos sprites invisibles mejor
  code/__DEFINES/misc.dm
  icons/hispania/mob/clothing/belt.dmi
  icons/hispania/mob/clothing/gloves.dmi
  icons/hispania/mob/clothing/head/beret.dmi
  icons/hispania/mob/clothing/head/hats.dmi
  icons/hispania/mob/clothing/head/helmet.dmi
  icons/hispania/mob/clothing/shoes.dmi
  icons/hispania/mob/clothing/species/grey/belt.dmi
  icons/hispania/mob/clothing/species/grey/gloves.dmi
  icons/hispania/mob/clothing/species/grey/head/beret.dmi
  icons/hispania/mob/clothing/species/grey/head/hats.dmi
  icons/hispania/mob/clothing/species/grey/head/helmet.dmi
  icons/hispania/mob/clothing/species/grey/shoes.dmi
  icons/hispania/mob/clothing/species/grey/suits/armor.dmi
  icons/hispania/mob/clothing/species/grey/suits/jacket.dmi
  icons/hispania/mob/clothing/species/grey/under/security.dmi
  icons/hispania/mob/clothing/species/vox/gloves.dmi
  icons/hispania/mob/clothing/species/vox/head/beret.dmi
  icons/hispania/mob/clothing/species/vox/head/hats.dmi
  icons/hispania/mob/clothing/species/vox/head/helmet.dmi
  icons/hispania/mob/clothing/species/vox/shoes.dmi
  icons/hispania/mob/clothing/species/vox/suits/armor.dmi
  icons/hispania/mob/clothing/species/vox/suits/jacket.dmi
  icons/hispania/mob/clothing/species/vox/under/security.dmi
  icons/hispania/mob/clothing/suits/armor.dmi
  icons/hispania/mob/clothing/suits/jacket.dmi
  icons/hispania/mob/clothing/under/security.dmi
  icons/hispania/obj/clothing/belt.dmi
  icons/hispania/obj/clothing/gloves.dmi
  icons/hispania/obj/clothing/head/berets.dmi
  icons/hispania/obj/clothing/head/hats.dmi
  icons/hispania/obj/clothing/head/helmet.dmi
  icons/hispania/obj/clothing/shoes.dmi
  icons/hispania/obj/clothing/suits/armor.dmi
  icons/hispania/obj/clothing/suits/jacket.dmi
  icons/hispania/obj/clothing/under/security.dmi
  modular_hispania/icons/mob/clothing/head/helmet.dmi
  modular_hispania/icons/mob/clothing/under/medical.dmi
  modular_hispania/icons/mob/clothing/under/security.dmi
Labels: Fix

#72 Dadaby!
  _maps/maphispania_files/dadaby/dadaby.dmm
  modular_hispania/modules/mapping/dadaby.dm
  paradise.dme
Labels: Mappeo, Héroe de Hispania

#70 Arreglos y modificaciones en el manejo de eventos
  code/modules/events/event.dm
  code/modules/events/event_container.dm
  code/modules/events/event_procs.dm
Labels: Tweak, Héroe de Hispania

#71 Vuelve Nations!!!
  code/__DEFINES/hud.dm
  code/__HELPERS/global_lists.dm
  code/datums/hud.dm
  code/modules/antagonists/_common/antag_hud.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/life.dm
  code/modules/mob/new_player/new_player.dm
  icons/mob/hud.dmi
  modular_hispania/code/__DEFINES/gamemode.dm
  modular_hispania/code/_globalvars/lists/mobs.dm
  modular_hispania/code/game/gamemodes/nations.dm
  modular_hispania/code/game/gamemodes/nations_defines.dm
  modular_hispania/code/game/gamemodes/nationsprocs.dm
  modular_hispania/code/modules/mob/living/silicon/robot/robot_modules.dm
  paradise.dme
Labels: Gamemode

#80 Ariete is back
  modular_hispania/code/game/objects/items/weapons/melee/misc.dm
  modular_hispania/sound/items/heavy_weapon_drop.ogg
  modular_hispania/sound/weapons/ram.ogg
  paradise.dme
Labels: Feature, Reconstruyendo la Sociedad de NUEVO

#75 Evento xenobiology breach habilitado
  code/modules/events/event_container.dm
Labels: Tweak, Evento
